bind F command-prompt { find-window -Z "%%" }
bind f display-popup -E -w "90%" -h "90%" -b none -s "bg=terminal" -S "bg=terminal,fg=#{@thm_overlay_0}" "tmux-sessionizer"
bind C-space last-window

bind l next-window
bind h previous-window

bind < swap-window -t -1\; select-window -t -1
bind > swap-window -t +1\; select-window -t +1

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind ^R source-file ~/.tmux.conf \; display-message "config reloaded"

bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send -X copy-selection-and-cancel

bind W display-popup -E -w "60%" -h "60%" -b none -s "bg=terminal" -S "bg=terminal,fg=#{@thm_overlay_0}" "\
  tmux list-windows -F '#{window_index}: #{window_name} (#{pane_current_command})' | \
  fzf --multi --header='Tab=select, Enter=kill' | \
  cut -d: -f1 | \
  xargs -I{} tmux kill-window -t {}"
