[ids]
*

[main]
capslock = overload(control, esc)
leftcontrol = f14
leftalt = layer(meta)
rightalt = layer(meta)
leftmeta = layer(alt)
rightmeta = layer(alt)

[meta]
leftshift = overload(shift, f13)
rightshift = overload(shift, f13)
