set -g prefix C-a
bind C-a last-window

set -g status-position bottom

set -g status-style bg=default
set -g status-left "\
#[fg=#{@thm_red},bold] SERVER \
#[fg=#{?client_prefix,#{@thm_red},#{@thm_mauve}}]#S\
#[bg=default,fg=#{@thm_surface_1}]  #(short-path \"#{pane_current_path}\")\
#[bg=default,fg=default]"
set -g status-right "#[fg=#{@thm_surface_1}]load #[fg=#{@thm_blue}]#(uptime | awk -F'load average: ' '{print $2}')"
set -g window-status-style "fg=#{@thm_surface_1}"
set -g window-status-current-style "fg=#{@thm_lavender} bold"
set -g status-left-length 100
set -g status-right-length 100
set -g status-justify absolute-centre
