# Status bar
set -g status-style bg=default
set -g status-left "\
#[fg=#{?client_prefix,#{@thm_red},#{@thm_mauve}}] #S\
#[bg=default,fg=#{@thm_surface_1}]  #(short-path \"#{pane_current_path}\")\
#[bg=default,fg=default]"
set -g status-right "#{?#{!=:#(org-clock-heading),},#[fg=#{@thm_surface_1}]#(org-clock-heading) #[fg=#{@thm_blue}]#(org-clock-time),#[fg=#{@thm_surface_1}]no active clock}"

set -g window-status-style "fg=#{@thm_surface_1}"
set -g window-status-current-style "fg=#{@thm_lavender} bold"

set -g status-left-length 100
set -g status-right-length 100
set -g status-justify absolute-centre

set -g status-position top

set -g prefix C-space 
bind C-space last-window

